### ISSUE TITLE
demo: alter db schema

### ISSUE THREAD

**Issue by evening** [evening/vtuber-tracker#4]
i care more about date than account.. so instead of
```
- profile_id:
  description:
  ..
  videos:
  - video_id:
     title: 
     description:
  - video_id 
```

maybe have two objects.. one with profile info, another with videos
```
- profile_id:
  description: ..

- videos:
  - video_id:
    title:
    author:
```
